.TH ECDSAKEYGEN "1" "June 2014" "ECDSA Utils" "User Commands"
.SH NAME
ecdsakeygen \- ECDSA key generation
.SH SYNOPSIS
.B ecdsakeygen
[\fI\,-s\/\fR] [\fI\,-p\/\fR] [\fI\,-h\/\fR]
.SH DESCRIPTION
ecdsautils
.TP
\fB\-s\fR
generate a new secret on stdout
.TP
\fB\-p\fR
output public key of secret read from stdin
.TP
\fB\-h\fR
display this short help and exit
.SH "SEE ALSO"
The full documentation for
.B ecdsakeygen
is in the source at
https://github.com/tcatm/ecdsautils
.SH AUTHOR
Nils Schneider
